Resources:
  SuveryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.suveryTableName}
      AttributeDefinitions:
        - AttributeName: surveyId
          AttributeType: S
      KeySchema:
        - AttributeName: surveyId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST