export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAIL = 'USER_SIGN_UP_FAIL';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAIL = 'USER_SIGN_IN_FAIL';

export const GET_STATISTICS_SUCCESS = 'GET_STATISTICS_SUCCESS';
export const GET_ORG_OVERVIEW_SUCCESS = 'GET_ORG_OVERVIEW_SUCCESS';
export const POST_SUVERY_SUCCESS = 'POST_SUVERY_SUCCESS';
export const UPDATE_SURVEY_FIELD = 'UPDATE_SURVEY_FIELD';
export const UPDATE_SURVEY_FORM = 'UPDATE_SURVEY_FORM';